name: Python package

on:
  schedule:
    - cron: '0 0-23 * * *' #runs at 00:00 UTC everyday

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - name: Run with setup-python 3.8
      uses: ./
      with:
        python-version: 3.8
    - name: Verify 3.8
      run: python __tests__/verify-python.py 3.8
    
    - name: Run scrapping
      run: |
        python main.py
