name: scrapping

on:
   push:
    branches: [ main ]
   pull_request:
     branches: [ main ]
   schedule:
     - cron:  '0 */15 * * *'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Execute Python script
        run: |
          python scripts/main.py

      - name: Add & Commit
        # You may pin to the exact commit or the version.
        # uses: EndBug/add-and-commit@b5dec7ea7647ed6edf307ec828d3aeb6bca69f63
        uses: EndBug/add-and-commit@v5.1.0
        with:
           # Arguments for the git add command
           add: # optional, default is .
           # The name of the user that will be displayed as the author of the commit
           author_name: # optional
           # The email of the user that will be displayed as the author of the commit
           author_email: # optional
           # Name of the branch to use, if different from the one that triggered the workflow
           branch: # optional
           # The directory where your repository is located. You should use actions/checkout first to set it up
           cwd: # optional, default is .
           # The message for the commit
           message: # optional
           # Arguments for the git rm command
           remove: # optional
           # Whether to use the --signoff option on git commit
           signoff: # optional
           # Arguments for the git tag command (the tag name always needs to be the first word not preceded by a hyphen)
           tag: # optional

      - name: commit changes
        run: |
          chmod +x ./scripts/commit.sh
          ./scripts/commit.sh
