name: scrapping

on:
   push:
    branches: [ main ]
   pull_request:
     branches: [ main ]
   schedule:
     - cron:  '0 */15 * * *'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Execute Python script
        run: |
          python scripts/main.py

      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: commit changes
        run: |
           git add .
           git commit -m "Updated Repository data"
           git push origin master
